services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - "./docker/data/postgres:/var/lib/postgresql/data"
      - "./test/create-database-postgres-gleam_cake_test.sql:/docker-entrypoint-initdb.d/1-create-database-postgres-gleam_cake_test.sql"
    ports:
      - 5432:5432
  mariadb:
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    environment:
      MARIADB_DATABASE: "gleam_cake_test"
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: true
