name = "cake"
version = "0.3.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.

description = "An SQL query builder for Gleam targeting Postgres and SQLite - a preview"
licences = ["AGPL-3.0-or-later"]
repository = { type = "github", user = "inoas", repo = "gleam-cake" }
# links = [{ title = "Website", href = "https://gleam.run" }]
gleam = ">= 1.2.0 and < 2.0.0"

[dependencies]
# act
# aragorn2
# based
# based_pg
# based_sqlite
# bigben
# blah
# carpenter
# cleam
# commonmark
# dot_env
# dotenv_gleam
# envoy
# exception
# fmt
# formal
# glam
# gleam_json
# gleamy_structures
# gleamyshell
# glearray
# glemo
# glenvy
# glevenshtein
# gluid
# go_over
# gsv
# hardcache
# html_lustre_converter
# kielet
# libsql
# logging = ">= 1.1.0 and < 2.0.0"
# lustre
# lustre_dev_tools
# lustre_ssg
# migrant
# mist
# mysql-otp maybe, but needs a gleam wrapper first
# nibble
# non_empty_list
# parallel_map
# phony
# prequel
# prng
# ranged_int
# ranger
# rank
# shellout
# spinner
# storch
# temporary
# tinyroute
# tom
# valid
# wisp
# youid
# comet = ">= 0.2.2 and < 2.0.0" # logging
# stacky = ">= 1.4.0 and < 2.0.0"

# TODO v2 wrap prepared statement in a catch, return Result
# TODO v2 run validator after building, return Result
# TODO v2 - hash the structure, safe hash as valid into cache
# TODO v2 - only run validator if no cache hit
# TODO v2 add all the prepared statement
# TODO v2 - add a client side caching layer
# TODO v2   - safe small results in cache
# TODO v2   - expire cache based on arg, which could also be 0 for no cache

gleam_erlang = ">= 0.25.0 and < 2.0.0"
gleam_stdlib = ">= 0.38.0 and < 2.0.0"

[dev-dependencies]
birdie = ">= 1.1.5 and < 2.0.0"
glacier = ">= 1.0.0 and < 2.0.0"
gleam_pgo = ">= 0.10.0 and < 2.0.0"
gmysql = ">= 1.0.0 and < 2.0.0"
pprint = ">= 1.0.3 and < 2.0.0"
sqlight = ">= 0.9.0 and < 2.0.0"

# glychee
# qcheck
# qcheck_gleeunit_utils
# testbldr
