name = "cake"
version = "0.1.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.

description = "An SQL query builder for Gleam targeting Postgres and SQLite - a preview"
licences = ["AGPL-3.0-or-later"]
repository = { type = "github", user = "inoas", repo = "gleam-cake" }
# links = [{ title = "Website", href = "https://gleam.run" }]
gleam = ">= 1.2.0 and < 2.0.0"

[dependencies]
# act
# aragorn2
# bigben
# blah
# carpenter
# cleam
# commonmark
# dot_env
# dotenv_gleam
# envoy
# exception
# fmt
# formal
# glam
# gleam_json
# gleamy_structures
# gleamyshell
# glearray
# glemo
# glenvy
# glevenshtein
# gluid
# go_over
# gsv
# hardcache
# html_lustre_converter
# kielet
# libsql
# lustre
# lustre_dev_tools
# lustre_ssg
# migrant
# mist
# mysql-otp maybe, but needs a gleam wrapper first
# nibble
# non_empty_list
# parallel_map
# phony
# prequel
# prng
# ranged_int
# ranger
# rank
# shellout
# spinner
# stacky
# storch
# tinyroute
# tom
# valid
# wisp
# youid
gleam_erlang = ">= 0.25.0 and < 2.0.0"
gleam_pgo = ">= 0.9.0 and < 2.0.0"
gleam_stdlib = ">= 0.38.0 and < 2.0.0"
sqlight = ">= 0.9.0 and < 2.0.0"

[dev-dependencies]
birdie = ">= 1.1.5 and < 2.0.0"
glacier = ">= 1.0.0 and < 2.0.0"
# glychee
pprint = ">= 1.0.3 and < 2.0.0"
# qcheck
# qcheck_gleeunit_utils
# testbldr
