name = "cake"
version = "0.1.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.

description = "An SQL query builder for Gleam targeting Postgres and SQLite - preview"
licences = ["AGPL-3.0-or-later"]
repository = { type = "github", user = "inoas", repo = "cake" }
# links = [{ title = "Website", href = "https://gleam.run" }]

[dependencies]
# act
# bigben
# blah
# carpenter
# cleam
# dot_env
# dotenv_gleam
# envoy
# exception
# fmt
# formal
# glam
# gleam_json
# gleamy_structures
# glearray
# glemo
# glenvy
# gluid
# gsv
# html_lustre_converter
# kielet
# libsql
# lustre
# lustre_dev_tools
# lustre_ssg
# migrant
# mist
# nibble
# non_empty_list
# parallel_map
# phony
# prequel
# prng
# ranged_int
# ranger
# rank
# shellout
# spinner
# stacky
# tom
# valid
# wisp
# youid
gleam_erlang = ">= 0.25.0 and < 2.0.0"
gleam_pgo = ">= 0.9.0 and < 2.0.0"
gleam_stdlib = ">= 0.37.0 and < 2.0.0"
sqlight = ">= 0.9.0 and < 2.0.0"

[dev-dependencies]
birdie = ">= 1.1.5 and < 2.0.0"
glacier = ">= 1.0.0 and < 2.0.0"
# glychee
pprint = ">= 1.0.3 and < 2.0.0"
# qcheck
# qcheck_gleeunit_utils
# testbldr
