name = "cake"
version = "0.0.1"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
# description = ""
# licences = ["Apache-2.0"]
# repository = { type = "github", user = "username", repo = "project" }
# links = [{ title = "Website", href = "https://gleam.run" }]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
# act = ">= 0.3.0 and < 2.0.0"
# bigben
# birl
# blah
# carpenter = ">= 0.3.1 and < 2.0.0"
# cleam
# dotenv_gleam
# envoy = ">= 1.0.1 and < 2.0.0"
# exception = ">= 2.0.0 and < 3.0.0"
# fmt = ">= 0.1.0 and < 2.0.0"
# glam
# gleam_erlang = ">= 0.25.0 and < 2.0.0"
# gleam_json = ">= 1.0.0 and < 2.0.0"
# gleam_pgo = ">= 0.7.0 and < 2.0.0"
# gleamy_structures = ">= 0.4.1 and < 2.0.0"
# glearray = ">= 0.2.1 and < 2.0.0"
# glenvy
# gluid
# gsv = ">= 1.4.0 and < 2.0.0"
# libsql
# migrant
# nibble
# non_empty_list
# parallel_map = ">= 1.0.0 and < 2.0.0"
# prequel
# prng = ">= 3.0.2 and < 4.0.0"
# ranged_int = ">= 2.0.0 and < 3.0.0"
# ranger = ">= 1.2.0 and < 2.0.0"
# rank = ">= 1.0.0 and < 2.0.0"
# shellout = ">= 1.6.0 and < 2.0.0"
# spinner = ">= 1.1.0 and < 2.0.0"
# youid = ">= 1.0.0 and < 2.0.0"
# tom = ">= 0.3.0 and < 2.0.0"
# dot_env = ">= 0.5.1 and < 2.0.0"
# envoy = ">= 1.0.1 and < 2.0.0"
# qcheck_gleeunit_utils
# qcheck
# non_empty_list = ">= 1.1.1 and < 2.0.0"
#
gleam_stdlib = ">= 0.36.0 and < 2.0.0"
sqlight = ">= 0.9.0 and < 2.0.0"
gleam_pgo = ">= 0.7.0 and < 1.0.0"
gleam_erlang = ">= 0.25.0 and < 1.0.0"

[dev-dependencies]
# glychee = ">= 1.1.0 and < 2.0.0"
# birdie = ">= 1.1.3 and < 2.0.0"
glacier = ">= 1.0.0 and < 2.0.0"
pprint = ">= 1.0.1 and < 2.0.0"
# qcheck = ">= 0.0.1 and < 2.0.0"
