name: Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_call:

jobs:
  test:
    uses: ./.github/workflows/abstract/test
    with:
      gleam_version: "1.2.1"
      otp_version: "27.0"
      test_erlang: true
      test_node: false
